"""add subscribe table

Revision ID: df0aed02b0f0
Revises: 4f661b2f0aed
Create Date: 2022-10-13 17:48:02.706559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df0aed02b0f0'
down_revision = '4f661b2f0aed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscribe',
    sa.Column('fan_id', sa.Integer(), nullable=True),
    sa.Column('contributor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contributor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['fan_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscribe')
    # ### end Alembic commands ###
